config/routes.rb
Rails.application.routes.draw do
  root 'landing#home'
  get 'ap/:id' => 'landing#asset_provider', as: :asset_provider
  get 'ap/:ap_id/f/:f_id' => 'landing#asset_provider_fund', as: :asset_provider_fund
  get 'ap/:ap_id/f/:f_id/s/:s_id' => 'landing#series_details', as: :series_details
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_controller.rb
# frozen_string_literal: true

class LandingController < ApplicationController
  def home
    @asset_providers = asset_providers
  end

  def asset_provider
    asset_provider_id = params[:id]
    @asset_provider = fintual.asset_provider(asset_provider_id)
    @funds = fintual.asset_provider_funds(asset_provider_id)
  end

  def asset_provider_fund
    asset_provider_id = params[:ap_id]
    @fund_id = params[:f_id]
    @asset_provider = fintual.asset_provider(asset_provider_id)
    @series = fund_series(@fund_id)
    @fund_name = @series.first[:fund_name]
  end

  def series_details
    asset_provider_id = params[:ap_id]
    fund_id = params[:f_id]
    @asset_provider = fintual.asset_provider(asset_provider_id)
    @fund = fintual.fund(fund_id)
    @series_id = params[:s_id]

    #@days = fintual.series_days(serie_id)
  end

  private

  def fintual
    @fintual = FintualClient.new
  end

  def asset_providers
    @asset_providers ||= begin
      result = fintual.asset_providers.map do |ap|
        {
          id: ap[:id],
          short_name: ap[:attributes][:name].remove('ADMINISTRADORA GENERAL DE FONDOS')
        }
      end
      result.sort_by { |r| r[:name] }
    end
  end

  def fund_series(fund_id)
    @fund_series ||= begin
      result = fintual.fund_series(fund_id).map do |s|
        last_day = s[:attributes][:last_day]
        {
          id: s[:id],
          fund_name: s[:attributes][:name],
          serie: s[:attributes][:serie].titleize,
          date: last_day[:date],
          fixed_fee:  to_annual_fee(last_day[:fixed_fee]),
          variable_fee: to_annual_fee(last_day[:variable_fee])
        }
      end
      result.sort_by { |s| s[:serie] }
    end
  end

  def to_annual_fee(daily_fee)
    return 'n/a' if daily_fee.nil?

    (daily_fee * 360.0).to_s
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/_list_asset_providers.html.erb
 <%if @asset_providers.present? %>
  <p>Below is the list  </p>
  <table width="100%">
    <tr>
      <td>ID</td>
      <td>Nombre</td>
    </tr>
    <% @asset_providers.each do |u|%>
    <tr>
      <td><%=u[:id]%></td>
      <td><%=u[:attributes][:name]%></td>
    </tr>
   <%end%>
  </table>
<%else%>
  <p>No Bank is Found</p>
<%end%>

app/views/landing/asset_provider.html.erb
<h2><%= @asset_provider[:attributes][:name] %></h2>

<h3> Elige un fondo mutuo para ver más detalles</h3>

<ul>
  <% @funds.each do |f|%>
    <li><%= link_to(f[:attributes][:name].titleize,
            asset_provider_fund_path(ap_id: @asset_provider[:id], f_id: f[:id]))
        %>
    </li>
  <%end%>
</ul>

app/views/landing/asset_provider_fund.html.erb
<h2><%= @asset_provider[:attributes][:name] %></h2>


<% if @series.empty? %>
  <p>No hay series para el fondo elegido</p>
<% else %>
  <h2><%= @fund_name.titleize %></h2>
  <h3>Detalles comisiones</h3>
  <ul>
    <% @series.each do |s|%>
      <li><b><%= link_to "Serie #{s[:serie]}",
                    series_details_path(ap_id: @asset_provider[:id],
                                        f_id: @fund_id,
                                        s_id: s[:id]) %>
          </b>
      </li>
      <ul>
      <li>Fecha: <%= s[:date] %></li>
      <li>Comisión fija: %<%= s[:fixed_fee] %></li>
      <li>Comisión variable: %<%= s[:variable_fee] %></li>
      </ul>
    <%end%>
  </ul>
  <% end %>

app/views/landing/home.html.erb
<h1>Que Fondo Mutuo</h1>

<h3> Elige una administradora para ver sus fondos</h3>

 <%= select_tag "asset_providers",
      options_for_select(@asset_providers.collect { |ap| [ap[:short_name], ap[:id]] })
 %> 

 
<ul>
  <% @asset_providers.each do |ap|%>
    <li><%= link_to(ap[:short_name].titleize, asset_provider_path(ap[:id])) %></li>
  <%end%>
</ul>

app/views/landing/series_details.html.erb
<h2><%= @asset_provider[:attributes][:name] %></h2>
<h2><%= @fund[:attributes][:name].titleize %></h2>

  <h3>Detalles serie</h3>
  <%= content_tag :div, nil,
     id: "series-graph",
     data: { seriesid: @series_id }
  %>

<%= javascript_pack_tag 'goograph' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.railstutorial.org/">Que Fondo Mutuo</a>
    por <a href="http://fintual.cl/">Fintual API</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar">
  <div class="container">
    <%= link_to "Que Fondo Mutuo", root_path%>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FfmmComparison</title>
    <%= csrf_meta_tags %>
 

    <%= csp_meta_tag %>
    <script type='text/javascript' src='https://www.gstatic.com/charts/loader.js'></script>
    <%= stylesheet_link_tag    'application', media: 'all'  %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
     <%= render 'layouts/header' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>